serverUpdateFrequency = 60
averageResolution = 1/6

SQL_HOST_IP = "192.168.50.2"
SQL_USER_NAME = "daq"
SQL_PASSWORD = "pass"

ARDUINO_PORT = "/dev/ttyACM0"
SOLAR_CHARGER_1_PORT = "/dev/ttyUSB0"
SOLAR_CHARGER_2_PORT = "/dev/ttyUSB1"
MODBUS_ADDRESS = 16

WIND_TURBINE_1_EFFICIENCY = .2 #*100%
WIND_TURBINE_1_RADIUS_METERS = 1 #m
WIND_TURBINE_1_AIR_DENSITY = 1.2 #kg/m^3

WIND_TURBINE_2_EFFICIENCY = .05 #*100%
WIND_TURBINE_2_RADIUS_METERS = 1 #m
WIND_TURBINE_2_AIR_DENSITY = 1.2 #kg/m^3